# Generated by Django 4.1.6 on 2023-02-07 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(max_length=50, verbose_name='Bloco')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('fonePess', models.CharField(max_length=15, verbose_name='Telefone Pessoal')),
                ('status', models.CharField(choices=[('a', 'Ativo'), ('i', 'inativo'), ('c', 'Cancelado'), ('b', 'Bloqueado')], max_length=1)),
                ('tipoPessoa', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('n', 'Nenhuma das opções')], max_length=1)),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('n', 'Nenhuma das opções')], max_length=1)),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=50, verbose_name='Bloco')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilitarios.bloco', verbose_name='Bloco')),
            ],
        ),
        migrations.CreateModel(
            name='ListaFone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fone', models.CharField(max_length=15, verbose_name='Fone/Ramal')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilitarios.bloco', verbose_name='Bloco')),
                ('pessoaLista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilitarios.pessoa', verbose_name='Colaborador')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilitarios.setor', verbose_name='Setor')),
            ],
        ),
    ]
