# Generated by Django 4.1.6 on 2023-02-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilitarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, verbose_name='Fone/Ramal')),
            ],
        ),
        migrations.RenameField(
            model_name='setor',
            old_name='setor',
            new_name='andar',
        ),
        migrations.AddField(
            model_name='listafone',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilitarios.area', verbose_name='Área'),
        ),
    ]
